config:
    network: 
        net: xception
    objective:
        O1: accuracy
        O2: inference_time
    index:
        O1: 0
        O2: 1
    online:
        remote:
            host: 10.173.131.123
            user: nvidia
            pass: nvidia 
            keyfile: key
            network: 
                code_dir: network.py
                model_dir: /home/tester/model.h5
                conf_dir: /home/tester/cur_config.yaml
        local:
            conf_dir: /home/nvidia/Shahriar/FlexiBO/cur_config.yaml
            model_dir: /home/nvidia/Shahriar/FlexiBO/models/model.h5    
        
    offline:
        measurement_dir: /home/nvidia/FlexiBO/measurements/trans.csv
    design_space:
        hardware:
            num_cores: [1,2,3,
                       4]
            core_freq: [345600, 806400,  1267200, 
                       1728000,2035200]
            gpu_freq: [114750000, 420750000, 726750000, 
                      1300500000]
            emc_freq: [40800000, 1062400000, 1866000000]
        os:
            cache_pressure: [0]
            swappiness: [10]
            dirty_background_ratio: [10]
            dirty_ratio: [5] 
        xception:
            entry_flow_num_filters: [ 16, 32, 64, 128, 256]
            entry_flow_filter_size: [1, 3, 5, 7, 9]
            middle_flow_num_filters: [16, 32, 64,128, 256]
            middle_flow_filter_size: [1, 3, 5, 7, 9]
            exit_flow_filter_size: [1, 3]
          
        lenet:
            layer1_num_filters: [16, 32, 64,
                                128, 256, 512, 
                                1024]
            layer1_filter_size: [1, 3, 5,
                                7, 9]
            layer2_num_filters: [16, 32, 64,
                                128, 256, 512, 
                                1024]
            layer2_filter_size: [1, 3, 5,
                                7, 9]
            layer3_num_filters: [16, 32, 64,
                                128, 256, 512, 
                                1024]
            layer3_filter_size: [1, 3, 5,
                                7, 9]
            layer4_num_filters: [16, 32, 64,
                                128, 256, 512, 
                                1024]
            layer4_filter_size: [1, 3, 5,
                                7, 9]

        mobilenet:
            stem_num_filters: [16, 32, 64,
                              128, 256, 512, 
                              1024]
            stem_filter_size: [1, 3, 5,
                               7, 9]
            depthwise_block1_num_filters: [16, 32, 64,
                                           128, 256, 512, 
                                           1024]
            depthwise_block2_num_filters: [16, 32, 64,
                                          128, 256, 512, 
                                          1024]
            depthwise_block3_num_filters: [16, 32, 64,
                                          128, 256, 512, 
                                          1024]
            depthwise_block4_num_filters: [16, 32, 64,
                                          128, 256, 512, 
                                          1024]
            
        resnet:
            stem_num_filters: [16, 32, 64,
                              128, 256, 512, 
                              1024]
            projection_block_num_filters: [16, 32, 64,
                                          128, 256, 512, 
                                          1024]
            projection_block_filter_size: [1, 3, 5,
                                          7, 9]
            bottleneck_block_num_filters: [16, 32, 64,
                                           128, 256, 512, 
                                           1024]
            bottleneck_block_filter_size: [1, 3, 5,
                                          7, 9]
                       
        squeezenet:
            stem_num_filters: [16, 32, 64,
                              128, 256, 512, 
                              1024]
            stem_filter_size: [1, 3, 5,
                              7, 9]
            fire_group1_num_filters: [16, 32, 64,
                                      128, 256, 512, 
                                      1024]
            fire_group2_num_filters: [16, 32, 64,
                                      128, 256, 512, 
                                      1024]
            fire_block_num_filters: [16, 32, 64,
                                     128, 256, 512, 
                                     1024]
            
        deepspeech:
            batch_size: [16, 32, 64,
                        128, 256, 512, 
                        1024]
            num_epochs: [10, 16,20,
                        24, 32,40,
                        48, 64, 96,
                        128, 200, 256,
                        512, 1024]
            dropout: [0.1, 0.2, 0.3,
                      0.4, 0.5]
        
        bert:
            batch_size: [6, 12, 14,
                        16, 32, 64]
            num_epochs: [10, 16,20,
                       24, 32,40,
                       48, 64, 96,
                       128, 200]
            dropout: [0.1,0.2, 0.3,
                      0.4, 0.5]
            max_seq_len: [13, 16, 32, 
                         64,128, 256,
                         512, 1024]
                 
        lstm:
            num_epochs: [10, 16,20,
                        24, 32,40,
                        48, 64, 96,
                        128, 200]
      
    systems:
        TX1:
            cpu:
                cores:
                    core0: cpu0
                    core1: cpu1
                    core2: cpu2
                    core3: cpu3
            
                frequency:
                    available: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
                    
            gpu:
                frequency:
                    available: /sys/kernel/debug/clock/gbus/possible_rates
                    current: /sys/kernel/debug/clock/gbus/rate
                status: /sys/kernel/debug/clock/gbus/state
        
            emc:
                frequency:
                    available: /sys/kernel/debug/clock/emc/possible_rates
                    current: /sys/kernel/debug/clock/emc/rate
                status: /sys/kernel/debug/clock/emc/state
        
       
            power:
                total: /sys/devices/platform/7000c400.i2c/i2c-1/1-0040/iio_device/in_power0_input
                gpu: /sys/devices/platform/7000c400.i2c/i2c-1/1-0040/iio_device/in_power1_input
                cpu: /sys/devices/platform/7000c400.i2c/i2c-1/1-0040/iio_device/in_power2_input
                                  
        TX2:
            cpu:
                cores:
                    core0: cpu0
                    core1: cpu3
                    core2: cpu4
                    core3: cpu5
            
                frequency:
                    available: /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
            
            gpu:
                frequency:
                    available: /sys/devices/17000000.gp10b/devfreq/17000000.gp10b/available_frequencies
                    current: /sys/devices/17000000.gp10b/devfreq/17000000.gp10b/cur_freq
                status: /sys/kernel/debug/bpmp/debug/clk/gpu/state
        
            emc:
                frequency:
                    available: /sys/kernel/debug/bpmp/debug/emc/possible_rates
                    current: /sys/kernel/debug/clk/emc/clk_rate
                status: /sys/kernel/debug/bpmp/debug/clk/emc/state
            power:
                total: /sys/devices/3160000.i2c/i2c-0/0-0040/iio:device0/in_power0_input
                gpu: /sys/devices/3160000.i2c/i2c-0/0-0040/iio:device0/in_power1_input
                cpu: /sys/devices/3160000.i2c/i2c-0/0-0040/iio:device0/in_power2_input
